---
- name: Setup fresh VMs
  hosts: k8s
  become: false
  gather_facts: false
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    # - name: Give ansible_user sudo permissions
    #   lineinfile:
    #     dest: /etc/sudoers
    #     line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    #     validate: "visudo -cf %s"

    - name: Update and upgrade
      become: true
      ansible.builtin.apt:
        update_cache: true
        autoclean: true
        upgrade: safe
      register: apt_upgrade
      notify: Apt_upgrade_change

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_iac.pub') }}"

    - name: Check if updates require reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: reboot_required.stat.exists

  handlers:
    - name: Apt_upgrade_change
      ansible.builtin.debug:
        var: apt_upgrade
