---
- name: Setup a k8s cluster masters
  hosts: masters
  become: false
  gather_facts: false
  vars:
    - calico_version: 3.25.0
  tasks:

    - name: Init cluster
      become: true
      ansible.builtin.shell: |
        kubeadm init --control-plane-endpoint={{ ansible_host }} --node-name={{ inventory_hostname }} --pod-network-cidr=10.224.0.0/24 > k8s_init.txt
      args:
        creates: /home/{{ ansible_user }}/k8s_init.txt

    - name: Create .kube directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: 0755

    - name: Copies admin.conf to user's kube config
      become: true
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        mode: 0755
        owner: "{{ ansible_user }}"
        remote_src: true

    - name: Check for Tigera Calico operator
      ansible.builtin.shell: |
        kubectl get pods --all-namespaces
      register: calico_installed
      changed_when: "'tigera-operator' in calico_installed.stdout"

    # Info: https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart
    - name: Install Tigera Calico operator (1/2)
      ansible.builtin.shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml
      when: not calico_installed.changed

    # Note: Before creating this manifest, read its contents and make sure its settings are correct for your environment.
    # For example, you may need to change the default IP pool CIDR to match your pod network CIDR.
    - name: Install Tigera Calico operator (2/2)
      ansible.builtin.shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/custom-resources.yaml
      when: not calico_installed.changed

    - name: Get the token for joining the worker nodes
      ansible.builtin.shell: |
        kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Output join command
      ansible.builtin.debug:
        var: kubernetes_join_command.stdout

    - name: Copy join command to local file (1/2)
      delegate_to: localhost
      ansible.builtin.file:
        path: ./kubernetes_join_command.txt
        mode: 0644
        state: touch

    - name: Copy join command to local file (2/2)
      delegate_to: localhost
      ansible.builtin.blockinfile:
        path: ./kubernetes_join_command.txt
        block: "{{ kubernetes_join_command.stdout_lines[0] }}"


    - name: Add admin.conf from control plane node to host (1/2)
      delegate_to: localhost
      ansible.builtin.file:
        path: ~/.kube/config
        mode: 0644
        state: touch

    - name: Add admin.conf from control plane node to host (2/2)
      become: true
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        flat: true
      register: admin_conf
