all:
  children:
    k8s:
      vars:
        ansible_user: iac
        ansible_password: iac
        ansible_sudo_pass: iac
        # ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q root@172.72.72.104"'
      children:
        masters:
          hosts:
            iac-k8s-m1:
              ansible_host: 172.72.72.108
        workers:
          hosts:
            iac-k8s-m2:
              ansible_host: 172.72.72.109
            iac-k8s-w1:
              ansible_host: 172.72.72.115
            iac-k8s-w2:
              ansible_host: 172.72.72.111
            iac-k8s-w3:
              ansible_host: 172.72.72.112
            iac-k8s-w4:
              ansible_host: 172.72.72.113
